// testapps/react-i18next/src/App.tsx
/* eslint-disable @typescript-eslint/no-var-requires */
import { Suspense } from 'react';
import { withTolgee } from '@tolgee/i18next';
import i18n from 'i18next';
import ICU from 'i18next-icu';
import { initReactI18next } from 'react-i18next';

import { Todos } from './Todos';
import { TranslationMethods } from './TranslationMethods';

withTolgee(i18n, {
  staticData: {
    en: () => import('./i18n/en.json'),
    de: () => import('./i18n/de.json'),
    fr: () => import('./i18n/fr.json'),
    cs: () => import('./i18n/cs.json'),
  },
  apiUrl: process.env.REACT_APP_TOLGEE_API_URL,
  apiKey: process.env.REACT_APP_TOLGEE_API_KEY,
})
  .use(ICU)
  .use(initReactI18next)
  .init({
    lng: 'en',
    supportedLngs: ['cs', 'en', 'fr', 'de'],
  });

export const App = () => {
  const currentRoute = window.location.pathname;

  return (
    <Suspense fallback={<div>Loading...</div>}>
      {currentRoute === '/translation-methods' ? (
        <TranslationMethods />
      ) : (
        <Todos />
      )}
    </Suspense>
  );
};

// testapps/vue/src/App.vue
<template>
  <TolgeeProvider :config="config">
    <template v-if="currentRoute === '/'">
      <Todos />
    </template>
    <template v-else>
      <TranslationMethods />
    </template>
    <template v-slot:fallback>
      <div>Loading...</div>
    </template>
  </TolgeeProvider>
</template>

<script lang="ts">
/* eslint-disable @typescript-eslint/no-var-requires */
import { defineComponent } from 'vue';
import { TolgeeProvider } from '@tolgee/vue';
import { TolgeeConfig } from '@tolgee/core';

import Todos from './Todos.vue';
import TranslationMethods from './TranslationMethods.vue';
import en from '../i18n/en.json';
import de from '../i18n/de.json';
import cs from '../i18n/cs.json';
import fr from '../i18n/fr.json';

export default defineComponent({
  name: 'App',
  components: { TolgeeProvider, Todos, TranslationMethods },
  data() {
    return {
      config: {
        staticData: { en, de, cs, fr },
        apiUrl: process.env.VUE_APP_TOLGEE_API_URL,
        apiKey: process.env.VUE_APP_TOLGEE_API_KEY,
        ui: process.env.VUE_APP_TOLGEE_API_KEY
          ? require('@tolgee/ui').UI
          : undefined,
      } as TolgeeConfig,
      currentRoute: window.location.pathname,
    };
  },
});
</script>
