// testapps/vue/src/Namespaces.vue
<template>
  <div class="background-wrapper">
    <div class="example">
      <Navbar>
        <div>
          <a href="/">The example app</a>
        </div>
      </Navbar>
      <template v-if="isLoading">Loading...</template>
      <template v-else>
        <div>{{ $t('test', { ns: 'base' }) }}</div>
        <div>{{ $t('test', { ns: 'test1' }) }}</div>
        <div>{{ $t('test', { ns: 'test2' }) }}</div>
        <div>{{ $t('test', { ns: 'test3' }) }}</div>
      </template>
    </div>
  </div>
</template>

<script lang="tsx" setup>
import { useTranslate } from '@tolgee/vue';
import Navbar from './components/Navbar.vue';

const { isLoading } = useTranslate(['base', 'test1', 'test2', 'test3']);
</script>

// testapps/svelte/src/routes/namespaces/+page.svelte
<script>
  import { getTranslate } from '@tolgee/svelte';
  import Navbar from '../../component/Navbar.svelte';

  const { t, isLoading } = getTranslate(['base', 'test1', 'test2', 'test3']);
</script>

<main class="translation-methods">
  <Navbar>
    <div slot="menu-items">
      <a href="/">The example app</a>
    </div>
  </Navbar>

  <div>
    {#if $isLoading}
      Loading namespace
    {:else}
      {$t('test')}
      {$t('test', { ns: 'test1'})}
      {$t('test', { ns: 'test2'})}
      {$t('test', { ns: 'test3'})}
    {/if}
  </div>
</main>
