// testapps/vue-i18next/src/App.vue
<template>
  <div v-waitForT>
    <template v-if="currentRoute === '/'">
      <Todos />
    </template>
    <template v-else>
      <TranslationMethods />
    </template>
  </div>
</template>

<script>
import Todos from './Todos.vue';
import TranslationMethods from './TranslationMethods.vue';

export default {
  name: 'App',
  components: { Todos, TranslationMethods },
  data() {
    return {
      currentRoute: window.location.pathname,
    };
  },
};
</script>

// packages/web/src/app/App.tsx
import { useEffect } from 'react';
import { useTolgee } from './basicTolgee';

import { Todos } from './Todos';
import { TranslationMethods } from './TranslationMethods';

export const App = () => {
  const currentRoute = window.location.pathname;
  const tolgee = useTolgee(['initialLoad']);

  useEffect(() => {
    tolgee.run();
  }, []);

  if (!tolgee.isLoaded()) {
    return null;
  }

  return (
    <>
      {currentRoute === '/translation-methods' ? (
        <TranslationMethods />
      ) : (
        <Todos />
      )}
    </>
  );
};
