// testapps/vue-i18next/src/components/LangSelector.vue
<template>
  <select
    v-bind="$i18n.i18next.language"
    @change="changeLanguage"
    class="lang-selector"
  >
    <option value="en">🇬🇧 English</option>
    <option value="cs">🇨🇿 Česky</option>
    <option value="fr">🇫🇷 Français</option>
    <option value="de">🇩🇪 Deutsch</option>
  </select>
</template>

<script>
export default {
  name: 'LanguageSelect',
  methods: {
    changeLanguage(e) {
      this.$i18n.i18next.changeLanguage(e.target.value);
    },
  },
};
</script>

// testapps/react-i18next/src/components/LangSelector.tsx
import React from 'react';
import { useTranslation } from 'react-i18next';

export const LangSelector: React.FC = () => {
  const { i18n } = useTranslation();

  return (
    <select
      className="lang-selector"
      onChange={(e) => i18n.changeLanguage(e.target.value)}
      value={i18n.language}
    >
      <option value="en">🇬🇧 English</option>
      <option value="cs">🇨🇿 Česky</option>
      <option value="fr">🇫🇷 Français</option>
      <option value="de">🇩🇪 Deutsch</option>
    </select>
  );
};
