// testapps/vue/src/components/LangSelector.vue
<template>
  <select
    :value="tolgee.getLanguage()"
    v-on:change="changeLanguage"
    class="lang-selector"
  >
    <option value="en">🇬🇧 English</option>
    <option value="cs">🇨🇿 Česky</option>
    <option value="fr">🇫🇷 Français</option>
    <option value="de">🇩🇪 Deutsch</option>
  </select>
</template>

<script setup>
import { useTolgee } from '@tolgee/vue';

const tolgee = useTolgee(['language', 'pendingLanguage']);

const changeLanguage = (e) => {
  tolgee.value.changeLanguage(e.target.value);
};
</script>

// testapps/react/src/components/LangSelector.tsx
import React from 'react';
import { useTolgee } from '@tolgee/react';

export const LangSelector: React.FC = () => {
  const tolgee = useTolgee(['pendingLanguage']);

  return (
    <select
      className="lang-selector"
      onChange={(e) => tolgee.changeLanguage(e.target.value)}
      value={tolgee.getPendingLanguage()}
    >
      <option value="en">🇬🇧 English</option>
      <option value="cs">🇨🇿 Česky</option>
      <option value="fr">🇫🇷 Français</option>
      <option value="de">🇩🇪 Deutsch</option>
    </select>
  );
};
