// testapps/react/src/components/LangSelector.tsx
import React from 'react';
import { useTolgee } from '@tolgee/react';

export const LangSelector: React.FC = () => {
  const tolgee = useTolgee(['pendingLanguage']);

  return (
    <select
      className="lang-selector"
      onChange={(e) => tolgee.changeLanguage(e.target.value)}
      value={tolgee.getPendingLanguage()}
    >
      <option value="en">🇬🇧 English</option>
      <option value="cs">🇨🇿 Česky</option>
      <option value="fr">🇫🇷 Français</option>
      <option value="de">🇩🇪 Deutsch</option>
    </select>
  );
};

// testapps/svelte/src/component/LangSelector.svelte
<script lang="ts">
  import { getTolgee } from '@tolgee/svelte';

  const tolgee = getTolgee(['pendingLanguage'])

  function handleLanguageChange(e: any) {
    $tolgee.changeLanguage(e.currentTarget!.value)
  }
</script>

<select value={$tolgee.getPendingLanguage()} on:change={handleLanguageChange} class="lang-selector">
  <option value="en">🇬🇧 English</option>
  <option value="cs">🇨🇿 česky</option>
  <option value="fr">🇫🇷 français</option>
  <option value="de">🇩🇪 Deutsch</option>
</select>
