// packages/react/src/TolgeeProvider.tsx
import * as React from 'react';
import { FunctionComponent, ReactNode, useEffect, useState } from 'react';
import { Tolgee, TolgeeConfig } from '@tolgee/core';

type ContextValueType = TolgeeConfig & { tolgee: Tolgee };
export const TolgeeProviderContext =
  React.createContext<ContextValueType>(null);
type TolgeeProviderProps = TolgeeConfig & { loadingFallback?: ReactNode };

export const TolgeeProvider: FunctionComponent<TolgeeProviderProps> = (
  props
) => {
  const config = { ...props };
  delete config.children;
  delete config.loadingFallback;

  const [tolgee] = useState(new Tolgee(config));

  const [loading, setLoading] = useState(tolgee.initialLoading);

  useEffect(() => {
    if (config.forceLanguage !== undefined) {
      tolgee.properties.config.forceLanguage = config.forceLanguage;
      tolgee.lang = config.forceLanguage;
    }
  }, [config.forceLanguage]);

  useEffect(() => {
    tolgee.run().then(() => setLoading(false));

    return () => {
      tolgee.stop();
    };
  }, []);

  return (
    <TolgeeProviderContext.Provider value={{ ...props, tolgee }}>
      {!loading ? props.children : props.loadingFallback}
    </TolgeeProviderContext.Provider>
  );
};

// packages/svelte/src/lib/TolgeeProvider.svelte
<script lang="ts">
  import { onDestroy, onMount, setContext } from "svelte";
  import { Tolgee, TolgeeConfig } from "@tolgee/core";
  import type { TolgeeContext } from "./getTolgeeContext";

  export let config: TolgeeConfig;

  const tolgee = new Tolgee(config || new TolgeeConfig());

  let tolgeeRunPromise: Promise<void>;

  setContext("tolgeeContext", {
    tolgee
  } as TolgeeContext);

  if (typeof window !== "undefined") {
    onMount(() => tolgeeRunPromise = tolgee.run());
    onDestroy(tolgee.stop);
  }
</script>

{#if !tolgee.initialLoading}
  <slot />
{:else}
  {#if !tolgeeRunPromise}
    <slot name="loading-fallback" />
  {:else }

    {#await tolgeeRunPromise}
      <slot name="loading-fallback" />
    {:then _}
      <slot />
    {/await}
  {/if}
{/if}
